# Generated by Django 4.2.4 on 2023-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='id',
            field=models.UUIDField(default='12506', editable=False, primary_key=True, serialize=False),
        ),
    ]
