# Generated by Django 4.2.4 on 2023-09-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0003_remove_productcategorymodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='cid',
            field=models.UUIDField(default='20475', editable=False, primary_key=True, serialize=False),
        ),
    ]
