# Generated by Django 4.2.4 on 2023-09-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0004_alter_productcategorymodel_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='cid',
            field=models.CharField(default='63669', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
